name: Hello World

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Say hello
      run: |
        echo "Hello World!"

