name: Triggered Workflow
on:
  workflow_run:
    workflows: ["Hello World"]
    types: 
      - completed
jobs:
  triggered-job1-parallel:
    runs-on: ubuntu-18.04
    steps:
    - name: Job1 Triggered
      run: |
        sleep 30s
        echo "I've been triggered by [${{ secrets.greeting }}] !"

  triggered-job2-parallel:
    runs-on: ubuntu-18.04
    steps:
    - name: Job2 Triggered
      run: |
        sleep 30s
        echo "I've been triggered by [${{ secrets.greeting }}] !"

  triggered-matrix-of-jobs-sequential:
    runs-on: ubuntu-18.04
    needs: triggered-job2-parallel
    strategy:
      fail-fast: false
      matrix:
        kube-runtime:
          - K3s-1.19
          - MicroK8s-1.19
          - Kubernetes-1.19
    steps:
    - name: ${{ matrix.kube-runtime }} Triggered
      run: |
        echo "${{ matrix.kube-runtime }} triggered by [${{ secrets.greeting }}] !"
